### ISSUE TITLE
Lernziel "Sie kennen den Zweck der IT im Unternehmen und kennen deren Hauptaufgaben"

### ISSUE THREAD

**Issue by simonerni** [wuethrich44/zusammenfassung-ssm#1]
Kannst Du mal schauen was dazu gehört? Ist das eher gemeint als Semester-Lernziel?

**Comment by alexsuter** [comment]
Ich werde am Samstag Kapitel 1-3 reviewen und ergänzen.

**Comment by alexsuter** [comment]
Wird im Task #27 erledigt
