### ISSUE TITLE
Kp 11 ITIL V3 & Vertiefung IT-Betrieb 

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-ssm#11]

**Comment by alexsuter** [comment]
@wuethrich44 
Ich hoffe du hesch da no nid agfange. Ich due im Issue #12 Event-Mgmt. und Monitoring beschriebe. De Kurmann hets zwar im Kp 11 dokumentiert, es isch aber Kapitel 12 verzellt worde.

**Comment by fabwu** [comment]
Oke tip top demfall machi en verwiess uf kp 12
