### ISSUE TITLE
Review Kp 4 Parallele Rechnerarchitekturen

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-ssm#20]

**Comment by simonerni** [comment]
@wuethrich44 Ready 4 Review. Bi de Implementation vo directory caches mit linked lists hani absolut kei ahnig, evt weisch du dett me?

**Comment by fabwu** [comment]
Das hani usegstriche will dr joho heds jo au nume vom blatt abglese :smile:

**Comment by fabwu** [comment]
Ich ha no domega netzwerk chli kürzt will ich denk da chunt nid so im detail aber chönschse au gern wider dri ne. Suscht sehr gued zämegfasst endlich tscheggi uma und numa!!
