### ISSUE TITLE
Stoffabgrenzung: Prüfen ob alle Kapitel berücksichtigt wurden.

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-ssm#30]

**Comment by alexsuter** [comment]
@wuethrich44 Minere Asicht na, isch jedes Kapitel dokumentiert. Bim Joho hani nid ganz so de durchblick, aber ich denke es isch alles dine? Casch au no churz checke?

**Comment by fabwu** [comment]
Ha mol alles chli dure gluegt aber ich glaub mir müend no recht chürze will 70 Site sind scho chli heavy... Ich drucks jetzt mol us und lieses dure
