### ISSUE TITLE
Unterschied Worload Embedding vs Workload Consolidation

### ISSUE THREAD

**Issue by simonerni** [wuethrich44/zusammenfassung-ssm#31]
Im Kapitel Server Virtualisierung - Abbildung 6.2 - > Vorteile Hypervisor 

Dort steht etwas von Workload Embedding und das Bild dazu ist so ein komischer PC Monitor (Terminal?)

Im Internet habe ich nichts gefunden...

**Comment by alexsuter** [comment]
Ich denke folgendes:

**Workload Consolidation** Ich habe mehrere physische Systeme, welche alle nicht voll ausgelastet sind. Jetzt kann ich alle einfach auf EIN physisches System konsolidieren.

**Workload Embedding** Ich vermute: Entweder dient es für _load balancing_ oder _Erhöhung der Verfügbarkeit_. Schau bei Workload Consolidation steht App1 und App2, also zwei unterschiedliche Applikationen. Hier steht zweimal App. Ich vermute es handelt um die selbe App. Ich denke, falls eine App ausfällt, dann springt die zweite ein. Bzw. wenn die eine VM ausfällt kommt die zweite zum Zug.

P.S. Dies stammt aus einem Microsoft Foliensatz... jedoch ohne Erklärung.

@wuethrich44 Du no en Idee?

**Comment by fabwu** [comment]
![image](https://cloud.githubusercontent.com/assets/6050639/8155055/7853a2a2-1340-11e5-82b5-f44f004aaab6.png)
 Mir sind scho uf google :hushed:

**Comment by fabwu** [comment]
Neui idee: Was meineder zu Sandboxes uf Embedded Devices (z.B. Android...)?

**Comment by fabwu** [comment]
Ich habe ein Mail an Joho geschrieben...

**Comment by simonerni** [comment]
Neue Vermutung; Workload Embedding meint, dass auf demselben Hypervisor zwei unterschiedliche Rechenarchitekturen virtualisiert (bzw. emuliert) werden können, d.h. einmal eine x86 und die andere eine PowerPC Architektur.

**Comment by fabwu** [comment]
Antwort von Joho:

> Das ist eine von Microsoft (!!) eingeführter Term. Damit wird gemeint, dass wenn 2 Applikationen mit gleichem Workload (zB DB oder App Server) auf der gleichen HW laufen diese durch den Hypervisor optimiert werden können.
