### ISSUE TITLE
Speicherallokation Begriffe

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-ssm#32]
Ich habe das versucht mal ein bisschen deutlicher darzulegen.

![image](https://cloud.githubusercontent.com/assets/7498380/8148439/ed0cc978-129d-11e5-88d2-c8008101ed1b.png)

Fragen:

Sind folgende Gedanken korrekt?

1.
Alloziert: Ich vergleiche das mit folgendem. Ich platziere auf die Disk eine VM mit 800 GB Speicher. Ich muss ja den Speicher vorgängig pro VM definieren.
Utilization: Beschreibt wie viel von der Allozierung tatsächlich gebraucht werden. Momentan wird halt nur 75% verwendet. In der VM habe ich also noch 25% Platz zur Verfügung um Daten zu speichern.

2.
Der Yield scheint immer ein Betrag zu sein oder eine Prozentzahl aber nie eine konkrete Speichermenge, wie bswp. 500GB?

3.
Kosten schlechter Qualität beschreibt nun wie viel Speicher (in Franken) einfach ungenutzt herumliegt. Oder?

4.
Für die COPQ in % Berechnung kommt noch eine Zahl dazu: 1'000'000$ Einnahmen auf 1000GB. Woher kommt diese Zahl? Nimmt man einfach die gesamten Einnahmen der Unternehmen und teilt sie durch den Speicher (in GB), welcher das Unternehmen besitzt?

**Comment by alexsuter** [comment]
1. Sollte stimmen
2. Stimmt.
3.  Auch richtig.
4. ''Der Ertrag der Firma wird ins Verhältnis mit dem Datenspeicher gelegt''. Die 1000000$ ist also der Ertrag der Firma.

**Comment by fabwu** [comment]
Ich probiere auch gerade aus diesen Begriffen schlau zu werden. Vor allem wie kommt man auf 51'200 $?

![image](https://cloud.githubusercontent.com/assets/6050639/8293190/182030d6-1934-11e5-9b84-9d0082071bd3.png)

**Comment by simonerni** [comment]
0.05 x 1024 x 1000

1 GB = 1024 MB ...
Fabian Wüthrich notifications@github.com schrieb am Mo., 22. Juni 2015 um
23:12:

**Comment by fabwu** [comment]
Ah jo verdammt IS isch scho es zitli her...

**Comment by fabwu** [comment]
Warum wird eigentlich nur 80% alloziert? Kommt das durch ein schlechtes Speichermgmt. zustande?

**Comment by simonerni** [comment]
80% sind gar nicht schlecht. Man denke sich ein Speichersystem, welches 99% ausgelastet ist, dann ist der Admin ja ständig bei digitec eine Festplatte am bestellen, weil das System schon wieder keinen Platz hat.
