### ISSUE TITLE
Vertikale vs. horizontale Skalierung

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-ssm#35]
im JOHO sim Skript staht:
- Horizontal Scalability (z.B: die Aufgabe auf mehr Prozessoren, die dazugefügt werden,
  verteilen).
- Vertical Scalability (z.B: die Aufgabe auf mehr Computersysteme, die dazugefügt werden,
  verteilen).

Uf Wikipedia staht genaus umgekehrte, und au da stahts umgekehrte?
https://de.wikipedia.org/wiki/Skalierbarkeit#Vertikale_Skalierung_.28scale_up.29
http://searchcio.techtarget.com/definition/vertical-scalability

shit oder?

**Comment by fabwu** [comment]
Also ich ha gmeint horizontal goht unendlich (Knoten hinzufügen) und vertikal isch Ressource i eim Node ufstocke (schnelleri CPU etc.). Demfall isches bim joho falsch...

Aber dr @red0point isch dr skalierigsspezialitscht :smile:

**Comment by alexsuter** [comment]
Ich has ebe au so denkt.

**Comment by simonerni** [comment]
Skalierungsexperte hier!

Nei bi au de Meinig, dass das vom Joho ned stimmt... Vorallem isch ja d vertikal skalierig gnau ned uf igndwas 'verteilen' sondern eifach grösseri chiste ane.

Naja. Wemmers em sege oder eifach wenns bide Prüfig setti dracho eifach uf Wiki usw. verwise?

**Comment by fabwu** [comment]
Chönschem jo gschwind alüte hesch jo sini numere :wink: 

Nei kei ahnig wer glaub scho nid schlecht wemene drufhiwiest aber uf mis mail heder au noni gantwortet
