### ISSUE TITLE
Sie wissen, was Snapshots sind, wo sie Vorteile haben und wo nicht

### ISSUE THREAD

**Issue by simonerni** [wuethrich44/zusammenfassung-ssm#37]
Was sind denn Bereiche wo Snapshots keine Vorteile haben?
## Vorteile:
- Konsistenter 'Schnappschuss' des Filesystems, auf den zurückgegriffen werden kann
- Kein 'Full Backup' des Systems notwendig
- Backup auf entfernte Systeme mit 'zfs send' möglich
- weitere?
## Nachteile:
- Wenn z.B. eine 500GB Datei gelöscht wird, verbraucht diese immer noch Platz auf der Festplatte, wenn ein Snapshot vorhanden ist, welcher diese 500GB Datei referenziert.
- weitere?

**Comment by simonerni** [comment]
Ähnlich das Lernziel

> Sie wissen, wozu Snapshots verwendet werden, wozu sie nicht zu gebrauchen sind und wieso diese in ZFS 'gratis anfallen.

Der Teil mit 'wozu sie nicht zu gebrauchen sind' - wozu sind denn Snapshots nicht zu gebrauchen? Zum Kochen, Kleider nähen oder Autofahren können sie nicht gebraucht werden, klar, aber... ?

**Comment by fabwu** [comment]
In den Kontrollfragen habe ich mir notiert, dass sich ein Snapshot nicht für Backups eignet, weil sich der Snapshot auf der gleichen Platte befindet.

**Comment by simonerni** [comment]
Ah achso, klar. Mit ZFS kann mann mit Snapshots ein inkrementelles Backup vom FS auch auf ein entferntes System machen, aber nur so per se sind Snapshots kein Backup, das verwirrt. Dankeschön
