### ISSUE TITLE
ZFS Interfaces

### ISSUE THREAD

**Issue by simonerni** [wuethrich44/zusammenfassung-ssm#38]
> Sie wissen, wie die Interfaces von ZFS definiert sind.

Ja, welche Interfaces denn?

**Comment by fabwu** [comment]
![image](https://cloud.githubusercontent.com/assets/6050639/8271368/d5790a1c-1813-11e5-84c3-78624dc82807.png)

Isch glaub die folie... Also zfs mit object und transactione
