### ISSUE TITLE
Review Kp 2 Data Center

### ISSUE THREAD

**Issue by simonerni** [wuethrich44/zusammenfassung-ssm#4]
Kannst du kurz drüberschauen + ergänzen?

**Comment by alexsuter** [comment]
Ich werde am Samstag Kapitel 1-3 reviewen und ergänzen.

**Comment by alexsuter** [comment]
shit huere viel

**Comment by alexsuter** [comment]
Formulierung entschärft im Kapitel 2.2.1
Eigenes Beispiel im Kapitel 2.2.1 eingefügt

**Comment by alexsuter** [comment]
sonst sehr gut, ich bin mir einfach nicht sicher ober utilization und allocation richtig verstandne haben, das hat er jedes mal anders erklärt.
